<?php

/**
 * Bootstrap the plugin, holds the information for WordPress.
 *
 * @package ASCDataRequeriments
 */

/**
 * Plugin Name: ASC Data Submission Requirements calculator
 * Plugin URI:  localhost
 * Author:      Kaio Souza
 * Description: This plugin creates the Data Submission Requirements calculator form suing the shortcode [DS_Form].
 * Version:     1.0.0
 * License:     MIT
 * License URL: https://mit-license.org/
 * text-domain: asc-data-requirements
 */

/**
 * Security measure avoid access outside WordPress.
 */
if ( ! defined( 'ABSPATH' ) ) {
	exit();
}

/**
 * Add rewrite rule for page.
 */
function ascds_rewrite_multilanguage() {
	global $wpdb;

	$sa_origin_path = '';

	$sa_page_id = wp_cache_get( 'sa_page_id' );

	if ( false === $sa_page_id ) {

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery -- much faster than get_page_by_path() or get_posts().
		$sa_page_id = $wpdb->get_var( "SELECT ID FROM {$wpdb->prefix}posts WHERE post_name='self-assessment'" );

		if ( isset( $sa_page_id ) ) {
			$sa_origin_path = get_permalink( $sa_page_id );
			$slug_path      = trim( str_replace( home_url(), '', get_permalink( $sa_page_id ) ), '/' );
			add_rewrite_rule( '^' . $slug_path . '/([^/]*)/?([^/]*)/?', 'index.php?page_id=' . $sa_page_id . '&satoken=$matches[1]&stage=$matches[2]', 'top' );

			wp_cache_set( 'sa_page_id', $sa_page_id, '', 3600 );
		}
	}

	flush_rewrite_rules( false );

	return array(
		'saOrigin' => $sa_origin_path,
	);
}

/**
 * Register styles an scripts, create a rewrite rule for query var, localize script for ajax use.
 */
function ascds_enqueue_scripts() {
	// $origin_path = ascds_rewrite_multilanguage();

	wp_register_style( 'dsStyle', plugins_url( '/assets/css/dsStyle.css', __FILE__ ), false, '1.0' );
	wp_register_style( 'gridStyle', plugins_url( '/assets/css/gridStyle.css', __FILE__ ), false, '1.0' );

	wp_register_script( 'dsScript', plugins_url( '/assets/js/dsScript.js', __FILE__ ), array( 'jquery', 'wp-i18n' ), '1.0', true );

	wp_register_style( 'select2css', 'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css', false, '1.0' );
	wp_register_script( 'select2js', 'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js', array( 'jquery' ), '1.0', true );

	// wp_register_style( 'bStyle', 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css', false, '1.0' );
	// wp_register_script( 'bScript', 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js', array( 'jquery' ), '1.0', true );

	wp_register_script( 'xlsxfull', plugins_url( '/assets/js/xlsxfull.min.js', __FILE__ ), false, '1.0', true );
	wp_register_script( 'xlsxstyle', plugins_url( '/assets/js/xlsx.bundle.js', __FILE__ ), false, '1.0', true );

	wp_register_style( 'bootstrapIcons', 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css', false, '1.0' );

	wp_localize_script(
		'dsScript',
		'dsDataDetail',
		array(
			'ajaxDetails' => admin_url( 'admin-ajax.php' ),
			'nonce'       => wp_create_nonce( 'ascds_nonce' ),
			// 'origin_path' => $origin_path['dsOrigin'],
		)
	);
}

/**
 * Implement SRI for styles.
 *
 * @param string $tag    HTML generated by WordPress for the style.
 * @param string $handle WordPress Asset name as used in wp_register_style().
 * @param string $src    The source URL for this (external) stylesheet.
 *
 * @return mixed|string
 */
function ascds_custom_style_attr( $tag, $handle, $src ) {
	// phpcs:disable WordPress.WP.EnqueuedResources.NonEnqueuedStylesheet -- this is an enqueued stylesheet.
	if ( 'bootstrapIcons' === $handle ) {
		$tag = '<link id="bootstrapIcons"  rel="stylesheet" href="' . esc_url( $src ) . '" integrity="sha384-Ay26V7L8bsJTsX9Sxclnvsn+hkdiwRnrjZJXqKmkIDobPgIIWBOVguEcQQLDuhfN" crossorigin="anonymous">';
	}
	if ( 'select2css' === $handle ) {
		$tag = '<link id="select2css"  rel="stylesheet" href="' . esc_url( $src ) . '" integrity="sha384-OXVF05DQEe311p6ohU11NwlnX08FzMCsyoXzGOaL+83dKAb3qS17yZJxESl8YrJQ" crossorigin="anonymous">';
	}

	if ( 'bStyle' === $handle ) {
		$tag = '<link id="bStyle"  rel="stylesheet" href="' . esc_url( $src ) . '" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">';
	}

	// phpcs:enable WordPress.WP.EnqueuedResources.NonEnqueuedStylesheet -- resume checking.

	return $tag;
}

/**
 * Implement SRI for scripts.
 *
 * @param string $tag    HTML generated by WordPress for the script.
 * @param string $handle WordPress Asset name as used in wp_register_script().
 * @param string $src    The source URL for this (external) script.
 *
 * @return mixed|string
 */
function ascds_custom_script_attr( $tag, $handle, $src ) {
	// phpcs:disable WordPress.WP.EnqueuedResources.NonEnqueuedScript -- this is an enqueued script.
	if ( 'select2js' === $handle ) {
		$tag = '<script id="select2js" src="' . esc_url( $src ) . '" integrity="sha384-d3UHjPdzJkZuk5H3qKYMLRyWLAQBJbby2yr2Q58hXXtAGF8RSNO9jpLDlKKPv5v3" crossorigin="anonymous"></script>';
	}

	if ( 'bScript' === $handle ) {
		$tag = '<script id="bScript" src="' . esc_url( $src ) . '" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>';
	}

	// phpcs:enable WordPress.WP.EnqueuedResources.NonEnqueuedScript -- resume checking.

	return $tag;
}

/**
 * Run the ajax process in class-fetchindicators.php with nonce security.
 */
function ascds_ajax_process() {
	check_ajax_referer( 'ascds_nonce' );

	if ( ! defined( 'ASC_MONGO_APIKEY' ) ) {
		echo 'Please define ASC_MONGO_APIKEY in wp-config.php';
		die();
	}

	include_once plugin_dir_path( __FILE__ ) . 'class-fetchrequireddata.php';

	if ( isset( $_SERVER['REQUEST_METHOD'] ) ) {
		if ( 'POST' === $_SERVER['REQUEST_METHOD'] ) {
			$fetchdata = new FetchRequiredData();

			// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- This is JSON data as received from the API. We should not escape it.
			echo wp_json_encode( $fetchdata->api_call( ASC_MONGO_APIKEY ) );
		} else {
			header( 'Location:' . home_url() );
			die();
		}
	}
	die();
}

/**
 * Creates the form.
 */
function ascds_form() {
	wp_enqueue_script( 'jquery' );

	wp_enqueue_style( 'select2css' );
	wp_enqueue_script( 'select2js' );

	// wp_enqueue_style( 'bStyle' );
	// wp_enqueue_script( 'bScript' );

	wp_enqueue_script( 'xlsxfull' );
	wp_enqueue_script( 'xlsxstyle' );

	wp_enqueue_style( 'bootstrapIcons' );

	wp_enqueue_style( 'gridStyle' );
	wp_enqueue_style( 'dsStyle' );
	wp_enqueue_script( 'dsScript' );

	$form = '
		<div class="container" id="pg-body">

			<div class="row">
				<div class="col-12 mb-3 mt-2" style="text-align: center;">
					<h2 class="asctitle">Welcome to the ASC Data Submission Requirements calculator</h2>
				</div>
			</div>

			<div class="row mb-4">
				<div class="col-12 mb-3">
					<span>Data reporting requirements are identified throughout the ASC Farm Standard.</span>
				</div>
				<div class="col-12 mb-3">
					<span>Data is submitted through the <a href="https://myasc.asc-aqua.org/login/" target="_blank">MyASC Certification Portal</a> 
					and shall adhere to the <a href="https://programme-centre.asc-aqua.org/app/uploads/2025/05/ASC-PRC-005-ASC-Data-Submission-Procedure-V1.0-May-2025.pdf" target="_blank">ASC Data Submission Procedure</a>. 
					If you are a producer and need access to the portal or have related questions, please contact: <a href="mailto: data@asc-aqua.org"> data@asc-aqua.org</a>.
					</span>
				</div>
				<div class="col-12 mb-3">
					<span>Data reporting requirements under the ASC Farm Standard vary depending on the:</span>
					<ul style="list-style-type: disc;">
						<li><strong>Species group</strong></li>
						<li><strong>Production system type</strong></li>
						<li>the <strong>Water type</strong> the farm is located in,</li>
						<li>whether the species is <strong>Feed dependent</strong>,</li>
						<li>the receiving <strong>Waterbody type</strong>, and</li>
						<li>the <strong>Production method</strong>.</li>
					</ul>
				</div>
				<div class="col-12 mb-1">
					<span>Use the filters to isolate the data reporting requirements applicable based on the variables of your system.</span>
					<span><strong>Appendix 2a</strong> details the reporting topics with their associated indicator numbers, a link to the required reporting templates and webforms, the frequency and timing of submission as well as the reporting level and temporal coverage.</span>
					<span><strong>Appendix 3a</strong> details all the attributes associated with the reporting requirements of the ASC Farm Standard.</span>
				</div>
			</div>

			<div id="filterbox" class="row ascfilter mb-3">
				<span class="ascfilterheader">Please select your applicability</span>

				<div class="row mt-2" style="margin: auto;">

					<div class="col-12 col-md-4 mt-2">
						<div class="asc-input">
							<label class="form-label ascfilterlabel">Species group</label>
							<select class="form-select" id="sp">
								<option></option>
								<option value="Abalone">Abalone</option>
								<option value="Bivalves">Bivalves</option>
								<option value="Cleaner_Fish">Cleaner fish</option>
								<option value="Crayfish">Crayfish</option>
								<option value="Flatfish">Flatfish</option>
								<option value="Freshwater_Prawn">Freshwater prawn</option>
								<option value="Pangasius">Pangasius</option>
								<option value="Pike_Perch">Pike perch</option>
								<option value="Salmonids_Freshwater">Salmonids freshwater</option>
								<option value="Salmonids_Marine">Salmonids marine</option>
								<option value="Seabass_Seabream_Meagre">Seabass, Seabream, Meagre</option>
								<option value="Seriola_Cobia">Seriola and Cobia</option>
								<option value="Shrimp">Shrimp</option>
								<option value="Tilapia">Tilapia</option>
							</select>
						</div>
					</div>
					
					<div class="col-12 col-md-4 mt-2">
						<div class="asc-input">
							<label class="form-label ascfilterlabel">Production System</label>
							<select class="form-select" id="psys">
								<option></option>
								<option value="Cages">Cages</option>
								<option value="Flowthrough_Raceway">Flowthrough / Raceway</option>
								<option value="Other_Water_Based">Other water based</option>
								<option value="Other_Land_Based">Other land based</option>
								<option value="Ponds">Ponds</option>
								<option value="Suspended">Suspended</option>
							</select>
						</div>
					</div>

					<div class="col-12 col-md-4 mt-2">
						<div class="asc-input">
							<div class="tooltipasc">
								<label class="form-label ascfilterlabel">Production Method <i class="bi bi-info-circle"></i></label>
								<span class="tooltipasctext" style="font-weight: 500;">
									ASC makes the distinction between "All-in all-out" production and "Continuous" production.
									<br><br>
									<strong>All-in all-out:</strong> is equal to batch production, where there is a distinct stocking and harvest event. All animals in the production unit are in homogeneous developmental stages (same size/age/year class).
									<br><br>
									<strong>Continuous:</strong> Stocking and harvesting may occur continuously during the year within the production unit. Animals within the production unit may vary in developmental stages.
								</span>
							</div>
							<select class="form-select" id="pmethod">
								<option></option>
								<option value="All_in_All_out">All-in All-out</option>
								<option value="Continuous">Continuous</option>

							</select>
						</div>
					</div>

				</div>

				<div class="row mt-2" style="margin: auto;">

					<div class="col-12 col-md-4 mt-2">
						<div class="asc-input">
							<label class="form-label ascfilterlabel">Water type</label>
							<select class="form-select" id="wland">
								<option></option>
								<option value="Brackish_Water">Brackish water</option>
								<option value="Freshwater">Freshwater</option>
								<option value="Marine_Water">Marine water</option>
							</select>
						</div>
					</div>

					<div class="col-12 col-md-4 mt-2">
						<div class="asc-input">
							<div class="tooltipasc">
								<label class="form-label ascfilterlabel">Waterbody type <i class="bi bi-info-circle"></i></label>
								<span class="tooltipasctext" style="font-weight: 500;">
									The waterbody type classification of the receiving body is based on Hydraulic Retention Time, Flow rate and Total Suspended Solids following the procedure of Appendix 8.5 of the ASC Farm Standard.
								</span>

							</div>
							<select class="form-select" id="wtype">
								<option></option>
								<option value="Type_A">Type A</option>
								<option value="Type_B">Type B</option>
								<option value="Type_C">Type C</option>
							</select>
						</div>
					</div>

					<div class="col-12 col-md-4 mt-2">
						<div class="asc-input">
							<label class="form-label ascfilterlabel">Feed Dependent</label>
							<select class="form-select" id="fd">
								<option></option>
								<option value="Fed">Fed</option>
								<option value="Non_Fed">Non Fed</option>
							</select>
						</div>
					</div>

				</div>

				<div class="row mt-4">
					<div class="col-12 mb-1" style="text-align: center;">
						<button type="button" id="startbtn" class="btn btnstart btn-lg">Calculate requirements</button>
					</div>
				</div>

			</div>

			<div id="content-result" class="row">
				<div id="btndiv" class="col-12 mb-2">
					<button id="exportbtn" class="btn btn-sm btnasc" style="float:right;">Export to Excel</button>
				</div>
				<div id="tablediv" class="col-12 mb-2" style="display: none;">
					<div id="resulttable" class="table-responsive ascborder" style="max-height: 400px;"></div>
				</div>
			</div>
			

		</div>
	';

	return $form;
	
}

add_action( 'init', 'ascds_enqueue_scripts' );
add_filter( 'style_loader_tag', 'ascds_custom_style_attr', 10, 3 );
add_filter( 'script_loader_tag', 'ascds_custom_script_attr', 10, 3 );

add_action( 'wp_ajax_ascds_ajax_process', 'ascds_ajax_process' );
add_action( 'wp_ajax_nopriv_ascds_ajax_process', 'ascds_ajax_process' );

add_shortcode( 'DS_Form', 'ascds_form' );
